version: '3.9'
volumes:
  influxdb_data:
services:
  influxdb:
    image: influxdb:1.8-alpine
    deploy:
      restart_policy:
        condition: any
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
